language: java
jdk: oraclejdk8
sudo: false
 
cache:
  directories:
    - ~/.m2

branches: 
 only:
 - master

before_install: 
 - git submodule foreach git pull origin master
# - mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=http://depot.universaal.org/maven-repo/thirdparty -Dartifact=org.slf4j:com.springsource.slf4j.api:1.5.0
# - mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=http://depot.universaal.org/maven-repo/thirdparty -Dartifact=org.slf4j:com.springsource.slf4j.log4j:1.5.0
 - chmod +x filter-maven-travis.sh
 - cd uAAL.pom
 
install:
 -
 
script:
 - ((((MAVEN_OPTS="-Xmx256m" mvn clean install -Dorg.ops4j.pax.logging.DefaultServiceLog.level=WARN; echo $? >&3) | ../filter-maven-travis.sh maven >&4) 3>&1) | (read xs; exit $xs)) 4>&1
# - mvn clean install -Dmaven.javadoc.skip=true -B
# - mvn clean install -Dmaven.javadoc.skip=true -B
# - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

notifications:
  email: false
