language: java
jdk: oraclejdk8
sudo: true
 
cache:
  directories:
    - ~/.m2

branches: 
 only:
 - master

env:
  global:
    secure: "dSVf9JLfkUsfi9c/atKC5KYE/yI4ERIkAYXYRN8PWQm5hQkJLPUzhGdt0XnhxgeCOFnmWkr7cc+dXu+z9Og3xHHAdRQB3puVxgTZHfGzUg4m1AKCOoVPb29kqdOvWJ3qNxzjVSIlYIf3AoinSKvIUnhDSt8mEAmt/g3XCinTjGMoQBcuFiNx4fk85rXhD4sA9Mexh+ftOT+mAupGuHiPj7BnCZhJfZ9M10jtMXEnqUqQjx5RKCdpdZSeED+YjkA+nBpWFYW8xDwEhOmSRNRF86WG/3wQGrPCXI0wvyGS1WDytFfk4cp1voxb3GcfKAH44oW5/CHwgm0oS/dVMlPNgBKWMLTGDLDk8zlh6Wrcy5vA2oPqqNor3sd4EcWvhhCgx7fuNQl5i4OEztD6MSaNzJEtowcV8Re+Ff7jUOHsHp2c62ncCSXG7CjzzGLIeSARMWWg3Ul2j7tL5LeuKXPCLJVDg9NQ4a0fiZgrpF0Q6778RQvu94K0U/j0CseTkU3jBpyf/xJz86ekFRwcbK8/c4nblugoshUMX/YwnWdeK8hGYvvsUA4Qx7/+4IwDYkkRmQjk52TPYOUpMm58SroLk3GI6nYkGqGK9Ss80LT8gsK/mQEqRa6eq4SxYEXi+W3/UWMVrNBL2av6zSlmgrBqW3MZYZ44OzgwB3NoGVOMEmk="

addons:
  apt:
    packages:
      - graphviz

before_install:
 - git submodule foreach git pull origin master
 - cd uAAL.pom
 - chmod +x src/scripts/push-to-gh-pages.sh
 - chmod +x src/scripts/codecov.sh
 - set -o pipefail
 - cp src/scripts/settings.xml $HOME/.m2/settings.xml

install:
 -

before_script:
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

script:
 - free -m
 - mvn clean install -DskipTests -Dorg.ops4j.pax.logging.DefaultServiceLog.level=WARN | grep -i "INFO] Build"
 - mvn javadoc:aggregate -fae | grep -i "INFO] Build"
 - mvn cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=xml -fae | grep -i "INFO] Build"
 - mvn cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=html -DskipTests -fae | grep -i "INFO] Build"
 - mvn site:site -DskipTests -Dcobertura.skip  -Dmaven.javadoc.skip=true -Duaal.report=ci-platform -fn -e
# - mvn site:stage -DstagingDirectory=$HOME/site/uAAL.pom -fn > /dev/null
# - echo Delete all coverage reports except the aggregated one!
# - mv target/site/cobertura/coverage.xml target/site/cobertura/coverage2.xml
# - find .. -name "coverage.xml" -type f -delete
# - mv target/site/cobertura/coverage2.xml target/site/cobertura/coverage.xml

after_success:
 - mvn deploy -N -DskipTests -DaltDeploymentRepository=uaal-nightly::default::http://depot.universaal.org/maven-repo/nightly/
 - export OLD_DIR=`pwd`
 - src/scripts/push-to-gh-pages.sh
 - cd "$OLD_DIR"
 - export GH_TOKEN="deleted"
 - export NIGHTLY_PASSWORD="deleted"
 - export NIGHTLY_USERNAME="deleted"
 - mvn org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report -e
 - src/scripts/codecov.sh

notifications:
  email: false
