language: java
jdk: oraclejdk8
sudo: false

cache:
  directories:
    - ~/.m2

branches: 
 only:
 - master

before_install: 
 - git submodule foreach git pull origin master
 - cd uAAL.pom

install:
 -
 
script:
 - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

notifications:
  email: false
