language: java
jdk: oraclejdk8
sudo: false
 
cache:
  directories:
    - ~/.m2

branches: 
 only:
 - master

before_install: 
 - git submodule foreach git pull origin master
 - mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=http://depot.universaal.org/maven-repo/thirdparty -Dartifact=org.slf4j:com.springsource.slf4j.api:1.5.0
 - cd uAAL.pom

install:
 -
 
script:
 - mvn clean install -Dmaven.javadoc.skip=true -B
# - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

notifications:
  email: false
