language: java
jdk: oraclejdk8

branches: 
 only:
 - master

before_install: 
 - git submodule foreach git pull origin master
 - cd uAAL.pom
 - ls

install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -rf :ri.api.manager.mysql
 
#script: mvn clean verify

notifications:
  email: false
